# Write a program to input eight numbers from the user and display all the unique numbers(once).
s=set()
n=input("Enter Number 1: ")
s.add(int(n))
n=input("Enter Number 2: ")
s.add(int(n))
n=input("Enter Number 3: ")
s.add(int(n))
n=input("Enter Number 4: ")
s.add(int(n))
n=input("Enter Number 5: ")
s.add(int(n))
n=input("Enter Number 6: ")
s.add(int(n))
n=input("Enter Number 7: ")
s.add(int(n))
n=input("Enter Number 8 ")
s.add(int(n))
print(s)